/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2018-12-10 07:04:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.boguco.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import memberlogin.memberBean;

public final class JoinPro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/boguco/pages/dropdown.jsp", Long.valueOf(1544371156779L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--출처: http://all-record.tistory.com/110?category=733042 [세상의 모든 기록]  -->\r\n");
      out.write("<!-- 위 출처를 바탕으로 상황에 맞도록 작성함. -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");

	request.setCharacterEncoding("UTF-8");
	//한글 깨짐 방지를 위한 코드.

      out.write("\r\n");
      out.write("<!-- 작성한 빈을 가져오는 코드! -->\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"../layout/styles/layout.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" media=\"all\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>가입을 축하드립니다!</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--유정연 : jsp파일 전체적인 css관리. ->상단부 , 하단부 링크 추가-->\r\n");
      out.write("\t<!--유정연 : 메뉴가 포함된 상단을 include-->\r\n");
      out.write("\t");
      out.write("<!-- 유정연 : iclude를 위한 상 하부를 따로 관리 -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("Template Name: Boguco\r\n");
      out.write("Author: <a href=\"https://www.os-templates.com/\">OS Templates</a>\r\n");
      out.write("Author URI: https://www.os-templates.com/\r\n");
      out.write("Licence: Free to use under our free template licence terms\r\n");
      out.write("Licence URI: https://www.os-templates.com/template-terms\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<!--외부 소스 : 외부 css 연결-->\r\n");
      out.write("<link href=\"../layout/styles/layout.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" media=\"all\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"wrapper row1\">\r\n");
      out.write("\t\t<header id=\"header\" class=\"hoc clear\">\r\n");
      out.write("\t\t\t<!-- ################################################################################################ -->\r\n");
      out.write("\t\t\t<div id=\"logo\" class=\"fl_left\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"../index.html\" style=\"font-weight: bold\">충공갱</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<!--사이트 이름-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<nav id=\"mainav\" class=\"fl_right\">\r\n");
      out.write("\t\t\t\t<ul class=\"clear\">\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"../index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<!--첫 화면-->\r\n");
      out.write("\t\t\t\t\t<li><a class=\"drop\">공지사항</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"cnu.jsp\">충남대 공지사항</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"cnuNew.jsp\">새소식</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"cnuBae.jsp\">학사정보</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"cnuEdu.jsp\">교육정보</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"cnu.jsp\">대학문화마당</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"dom.jsp\">기숙사 공지사항</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"dom.jsp\">은행사</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"domBac.jsp\">백행사</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"sw.jsp\">SW 사업단 공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"drop\"><a href=\"com.jsp\">컴퓨터공학과 공지사항</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"comBae.jsp\">학사정보</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"comBac.jsp\">일반소식</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"com.jsp\">사업단소식</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a class=\"drop\">키워드 알림</a> <!--키워드 알림 메뉴-->\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"submenu\"><a href=\"alarm.html\" target=\"iframe\">알림\r\n");
      out.write("\t\t\t\t\t\t\t\t\t설정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<!--알림 설정-->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"submenu\"><a href=\"alarmconfirm.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttarget=\"iframe\">알림 확인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<!--알림 확인-->\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!-- 여기까지가 메인페이지 윗 드롭다운 메뉴 설정. -->\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<!-- id파라미터는 id 프로퍼티로 적용하는 등 각각의 요소들을 모두 지정할 수 있다.-->\r\n");
      out.write("\t");
      memberlogin.memberBean memberBean = null;
      memberBean = (memberlogin.memberBean) _jspx_page_context.getAttribute("memberBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (memberBean == null){
        memberBean = new memberlogin.memberBean();
        _jspx_page_context.setAttribute("memberBean", memberBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("memberBean"), request);
      out.write("\r\n");
      out.write("\t<div class=\"wrapper row3\">\r\n");
      out.write("\t\t<main class=\"hoc container clear\"> <!-- main body --> <!-- ################################################################################################ -->\r\n");
      out.write("\t\t<h1>회원가입 확인</h1>\r\n");
      out.write("\t\t<!--회원가입 확인 코드!-->\r\n");
      out.write("\t\t<div id=\"join\">\r\n");
      out.write("\t\t\t<div id=\"wrapper\">\r\n");
      out.write("\t\t\t\t<br> <br> <b><font size=\"5\" color=\"gray\">회원가입\r\n");
      out.write("\t\t\t\t\t\t정보를 확인하세요.</font></b> <br> <br> <font color=\"blue\">");
      out.print(memberBean.getName());
      out.write("</font>님\r\n");
      out.write("\t\t\t\t가입을 축하드립니다. <br> <br>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"title\">아이디</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(memberBean.getId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"title\">비밀번호</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(memberBean.getPassword());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"title\">이름</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(memberBean.getName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"title\">생일</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(memberBean.getBirthday());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"title\">이메일</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(memberBean.getEmail());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"title\">휴대전화</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(memberBean.getPhone());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"title\">흥미사항</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(memberBean.getSubject());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<!--버튼을 누르면 로그인창으로 이동한다-->\r\n");
      out.write("\t\t\t\t<a href=\"join.html\"> <input type=\"button\" value=\"확인\"\r\n");
      out.write("\t\t\t\t\tclass=\"submit\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- ################################################################################################ -->\r\n");
      out.write("\t\t<!-- / main body -->\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</main>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<nav class=\"quicklinks row4\">\r\n");
      out.write("\t\t<ul class=\"hoc clear\">\r\n");
      out.write("\t\t\t<li><a href=\"../index.html\"><i class=\"fa fa-lg fa-home\"></i></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"about.html\">About</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://plus.cnu.ac.kr/html/kr/\">CNU</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://dorm.cnu.ac.kr/html/kr/\">Domitory</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://wise.cnu.ac.kr/\">SW</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"http://computer.cnu.ac.kr/\">Computer</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
